apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "ray-pvc-${PROJECT_NAME}"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 200Gi 