apiVersion: v1
kind: PersistentVolume
metadata:
  name: "ray-pv-${PROJECT_NAME}"
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "${FILE_SYSTEM_ID}" 