apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: cpu
spec:
  role: "KarpenterNodeRole-${CLUSTER_NAME}" 
  amiSelectorTerms:
    - alias: "al2023@v20250419"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME} 
  blockDeviceMappings:
    - deviceName: /dev/sda1
      ebs:
        encrypted: true
        volumeSize: 400Gi
        volumeType: gp3
        deleteOnTermination: true  