apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  role: "KarpenterNodeRole-${CLUSTER_NAME}"
  amiFamily: Custom
  amiSelectorTerms:
    - id: ${AMI_ID}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME}
  blockDeviceMappings:
    - deviceName: /dev/sda1
      ebs:
        encrypted: true
        volumeSize: 400Gi
        volumeType: gp3
        deleteOnTermination: true
  userData: |
    #!/bin/bash
    set -o xtrace

    # Install required packages for Ubuntu
    apt-get update
    apt-get install -y amazon-efs-utils

    # Configure kubelet for EKS
    /etc/eks/bootstrap.sh ${CLUSTER_NAME} \
      --kubelet-extra-args '--node-labels=ray_type=worker' \
      --apiserver-endpoint ${CLUSTER_ENDPOINT} \
      --b64-cluster-ca ${CLUSTER_CA_CERTIFICATE}