apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-${POOL_NAME}
spec:
  template:
    metadata:
      labels:
        ray_type: worker
        instance_type: ${INSTANCE_TYPE}
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["${INSTANCE_TYPE}"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu
      expireAfter: 720h
  limits:
    nvidia.com/gpu: 20
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m